# Generated by Django 4.2.7 on 2025-09-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Venue360Tour",
        ),
    ]
