# Generated by Django 4.2.7 on 2025-10-02 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20251003_0117"),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('user', 'Regular User'), ('manager', 'Event Manager'), ('admin', 'Administrator')], help_text='Role the user is requesting', max_length=10)),
                ('current_role', models.CharField(choices=[('user', 'Regular User'), ('manager', 'Event Manager'), ('admin', 'Administrator')], help_text="User's current role", max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Why the user wants this role upgrade')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes about the decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to='users.customuser')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='users.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userrolerequest',
            unique_together={('user', 'requested_role', 'status')},
        ),
    ]
