# Generated by Django 4.2.7 on 2025-10-02 20:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_create_user_role_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivity",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="emergency_contact_name",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="notification_email",
            new_name="email_notifications",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="notification_push",
            new_name="newsletter_subscription",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="email_verified",
            new_name="sms_notifications",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="emergency_contact_phone",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="emergency_contact_relationship",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="notification_sms",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="twitter_url",
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Tell us about yourself", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="experience_years",
            field=models.PositiveIntegerField(
                blank=True, help_text="Years of professional experience", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="job_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="languages",
            field=models.JSONField(
                blank=True, default=list, help_text="Languages you speak"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="linkedin_profile",
            field=models.URLField(blank=True, help_text="Your LinkedIn profile"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="specializations",
            field=models.JSONField(
                blank=True, default=list, help_text="Areas of expertise"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="twitter_handle",
            field=models.CharField(
                blank=True, help_text="Your Twitter handle (without @)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="website",
            field=models.URLField(blank=True, help_text="Your website or portfolio"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="IN", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.DeleteModel(
            name="EventManagerProfile",
        ),
        migrations.DeleteModel(
            name="UserActivity",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
