# Generated by Django 4.2.7 on 2025-07-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_eventreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Public events are visible to all users, private events are only visible to organizers",
            ),
        ),
    ]
