# Generated by Django 4.2.7 on 2025-09-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="guest_count",
            field=models.IntegerField(default=1, help_text="Number of guests"),
        ),
        migrations.AddField(
            model_name="registration",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="How they heard about the event",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="special_requirements",
            field=models.TextField(
                blank=True, help_text="Any special requirements or notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="terms_accepted",
            field=models.BooleanField(
                default=False, help_text="Terms and conditions accepted"
            ),
        ),
    ]
